# Generated by Django 4.2.5 on 2023-10-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=55)),
                ('lastname', models.CharField(max_length=55)),
                ('age', models.IntegerField(max_length=2)),
                ('email', models.CharField(max_length=55)),
            ],
        ),
    ]
