# Generated by Django 4.2.5 on 2023-10-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_form_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='form',
            name='fname',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='form',
            name='lname',
            field=models.CharField(max_length=55),
        ),
    ]
